# Generated by Django 3.2.7 on 2023-08-18 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_comments_location_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
