# Generated by Django 3.2.7 on 2023-08-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_report_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='participants',
            new_name='contributors',
        ),
    ]
