# Generated by Django 3.2.7 on 2023-08-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_participants_report_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='locate',
            field=models.CharField(max_length=250),
        ),
    ]
