# Generated by Django 3.2.7 on 2023-08-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_report_locate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Rimg',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
    ]
