# Generated by Django 3.2.7 on 2023-08-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_report_rimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Rimg',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
