# Generated by Django 3.2.7 on 2023-08-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20230820_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='images/'),
        ),
    ]
